language: python
dist: trusty
python:
    - "3.6"
    - "3.5"
addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test
    packages:
       - gfortran-7
script:
    - gfortran-7 --version
    - cd tests
    - make FC=gfortran-7
git:
  depth: 3
