language: python
dist: trusty
python:
    - "3.6"
    - "3.5"
addons:
  apt:
    packages:
      - gfortran
      - libblas-dev
      - liblapack-dev
      - libopenmpi-dev
      - openmpi-bin
script:
    - gfortran --version
    - cd tests
    - make
git:
  depth: 3
