language: python
dist: trusty
python:
    - "3.6"
    - "3.5"
addons:
  apt:
    packages:
      - gfortran
script:
    - apt-cache search gfortran
    - gfortran --version
    - cd tests
    - make
git:
  depth: 3
