language: python
dist: trusty
python:
    - "3.6"
    - "3.5"
addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test
    packages:
       - gfortran-8
script:
    - apt-cache search gfortran
    - gfortran --version
    - cd tests
    - make
git:
  depth: 3
